"function"!==typeof Object.create&&(Object.create=function(c){function n(){}n.prototype=c;return new n});
(function(c,n,h,f){var m={init:function(b,e){var a=this;a.elem=e;a.$elem=c(e);this.options=c.extend({},c.fn.bwlAccordion.config,b);a.options.pagination&&a.$elem.append('<input type="hidden" id="current_page"><input type="hidden" id="show_per_page"><div id="bsa_page_navigation" class="bsa_page_navigation" data-paginate="" data-pag_limit=""></div>');var d=a.get_animation_class();this.options.inAnimation=d[0];1==this.options.rtl&&a.addRTLSupport();a.displayAccordion();a.displaySearchBox();var g=a.$elem.find(".acc_title_bar"),
f=a.$elem.find(".accordion_search_input_box");1==this.options.ctrl_btn&&(a.$elem.find("section:first").before('<p class="acc-ctrl-btn"><span class="acc-expand-all"><i class="fa fa-plus"></i></span><span class="acc-collapsible-all"><i class="fa fa-minus"></i></span></p>'),this.options.acc_ctrl_btn=a.$elem.find(".acc-ctrl-btn"));""!=this.options.nav_box&&g.addClass("nav_"+this.options.nav_box);""!=this.options.nav_icon&&g.addClass("nav_icon_"+this.options.nav_icon);f.each(function(){c(this).val("").attr("placeholder",
a.options.placeholder);1==a.options.rtl?c(this).after('<span class="rtl_clear_btn"></span>'):c(this).after('<span class="acc_clear_btn"></span>')});var k=a.getThemeClasses(a.options.theme);a.searchEvent(k,d);g.on("click",function(){a.toggleEvent(c(this),k,d,a.$elem);return!1});(1==a.options.rtl?a.$elem.find(".rtl_clear_btn"):a.$elem.find(".acc_clear_btn")).on("click",function(){c(this).removeAttr("style");var b=a.$elem;b.find(".accordion_search_input_box").val("").attr("placeholder",a.options.placeholder);
a.removeHighlightEvent();a.resetAccordion(b,k,d)});1==this.options.ctrl_btn&&(g=a.$elem.find(".acc-expand-all"),f=a.$elem.find(".acc-collapsible-all"),g.on("click",function(){a.$elem.find("section").each(function(){c(this).find(".acc_title_bar").addClass(k.title_active_class).slideDown();c(this).find(".acc_container").slideDown(function(){c(this).find(".block").css({opacity:1}).addClass(d[0])})})}),f.on("click",function(){a.$elem.find("section").each(function(){c(this).find(".acc_title_bar").removeClass(k.title_active_class).slideDown();
c(this).find(".acc_container").slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(d[0])})})}))},generate_dynamic_css:function(b){var e=this.options.title_bg,a=this.options.title_text_color,d=this.options.nav_box_bg,g=this.options.title_active_bg,f=this.options.title_active_text_color,k=this.options.nav_active_box_bg;b="#"+b.attr("id");var l=b+" .theme-custom-title-bar{background: "+e+" !important;}"+(b+" .theme-custom-title-bar a {color: "+a+" !important;}")+(b+" .theme-custom-title-bar a:after {background: "+
d+" !important;}");l+=b+" .theme-custom-title-bar a:before {background: "+d+" !important;}";l+=b+" .theme-custom-title-bar a:hover {color: "+a+" !important;}";l+=b+" .theme-custom-title-bar a:hover:before {background: "+d+" !important;}";l+=b+" .theme-custom-title-active {background: "+this.bsaColorOpacity(g,15)+" !important;}";l+=b+" .theme-custom-title-active a {color: "+f+" !important;}";l+=b+" .theme-custom-title-active a:after {background: "+k+" !important;}";l+=b+" .theme-custom-title-active a:before {background: "+
k+" !important;}";l+=b+" .theme-custom-title-active a:hover {color: "+f+" !important;}";l+=b+" .theme-custom-title-active a:hover:before {background: "+k+" !important;}";l+=b+" div.theme-custom-title-active { background: #FFFFFF !important;}";c("<style>"+(l+(b+" .custom_theme_nav a.active_page { background: "+e+" !important; color: "+a+" !important;}"))+"</style>").appendTo("head")},get_url_parameter:function(b){for(var e=n.location.search.substring(1).split("&"),a=0;a<e.length;a++){var d=e[a].split("=");
if(d[0]==b)return d[1]}},bsaColorOpacity:function(b,e){var a=parseInt(b.substring(1,3),16),d=parseInt(b.substring(3,5),16),c=parseInt(b.substring(5,7),16);a=parseInt(a*(100+e)/100);d=parseInt(d*(100+e)/100);c=parseInt(c*(100+e)/100);a=255>a?a:255;d=255>d?d:255;c=255>c?c:255;a=1==a.toString(16).length?"0"+a.toString(16):a.toString(16);d=1==d.toString(16).length?"0"+d.toString(16):d.toString(16);c=1==c.toString(16).length?"0"+c.toString(16):c.toString(16);return"#"+a+d+c},addRTLSupport:function(){this.$elem.addClass("bwl_acc_container_rtl_support");
this.$elem.find(".acc_title_bar").addClass("rtl-title-bar");this.$elem.find(".accordion_search_input_box").addClass("search_icon_rtl")},displaySearchBox:function(){0==this.options.search?this.$elem.find(".accordion_search_container").remove():this.$elem.find(".accordion_search_container").css({display:"block"})},displayAccordion:function(){var b=this,e=b.getThemeClasses(b.options.theme);"custom"==b.options.theme&&b.generate_dynamic_css(b.$elem);b.$elem.find(".acc_title_bar").addClass(e.title_bar_class);
b.$elem.find(".acc_container").slideUp(100);b.$elem.find(".acc_container").find(".block").css({opacity:1}).addClass(b.options.inAnimation);if(0==b.options.closeall){var a=b.options.item_opened;"array"===c.type(a)?c.each(a,function(a,c){b.$elem.find(".acc_title_bar").eq(c).addClass(e.title_active_class).next().slideDown(700)}):"string"===c.type(a)?("even"===a?b.$elem.find(".acc_title_bar:even"):"odd"===a?b.$elem.find(".acc_title_bar:odd"):b.$elem.find(".acc_title_bar")).addClass(e.title_active_class).next().slideDown(700):
b.$elem.find(".acc_title_bar").eq(a).addClass(e.title_active_class).next().slideDown(700)}b.options.pagination&&b.$elem.find(".bsa_page_navigation").addClass(e.nav_class);if(b.options.pagination){a=b.$elem.find(".acc_container").length;var d=b.$elem,g=b.options.limit;d.find(".bsa_page_navigation").attr("data-paginate",b.options.pagination);d.find(".bsa_page_navigation").attr("data-pag_limit",b.options.limit);b.bsa_get_pagination_html(d,g,a)}},reset_acc_items:function(b,e){var a=this,d=a.options.item_opened;
if("array"===c.type(d))a.$elem.find(".acc_title_bar").removeClass(b.title_active_class).slideDown(),a.$elem.find(".acc_container").slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(e[0])}),c.each(d,function(d,f){a.$elem.find(".acc_title_bar").eq(f).addClass(b.title_active_class).slideDown();a.$elem.find(".acc_container").eq(f).slideDown(function(){c(this).find(".block").css({opacity:1}).addClass(e[0])})});else if("string"===c.type(d)){var g=a.$elem.find(".acc_title_bar:even"),
f=a.$elem.find(".acc_container:even"),k=a.$elem.find(".acc_title_bar:odd"),l=a.$elem.find(".acc_container:odd");"even"===d?(g.addClass(b.title_active_class).slideDown(),f.slideDown(function(){c(this).find(".block").css({opacity:1}).addClass(e[0])}),k.removeClass(b.title_active_class).slideDown(),l.slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(e[0])})):"odd"===d?(k.addClass(b.title_active_class).slideDown(),l.slideDown(function(){c(this).find(".block").css({opacity:1}).addClass(e[0])}),
g.removeClass(b.title_active_class).slideDown(),f.slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(e[0])})):(c([]).add(g).add(k).addClass(b.title_active_class).slideDown(),c([]).add(f).add(l).slideDown(function(){c(this).find(".block").css({opacity:1}).addClass(e[0])}))}else a.$elem.find(".acc_title_bar").eq(d).addClass(b.title_active_class).slideDown(),a.$elem.find(".acc_container").eq(d).slideDown(function(){c(this).find(".block").css({opacity:1}).addClass(e[0])}),a.$elem.find(".acc_title_bar").not(":eq("+
d+")").removeClass(b.title_active_class).slideDown(),a.$elem.find(".acc_container").not(":eq("+d+")").slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(e[0])})},bsa_get_pagination_html:function(b,e,a,d){var f=this,h=b.find(".bsa_page_navigation").data("paginate");if("undefined"!=typeof d&&1==d){if(1==h){d=b.find("section.filter");var k=d.length;d.slice(0,e);d.slice(e,k).css("display","none")}b.find("input[type=text]").removeClass("search_load").addClass("search_icon")}else b.find("section").css("display",
"none"),b.find("section").slice(0,e).css("display","block"),a=b.find("section").length;a=Math.ceil(a/e);b.find("#current_page").val(0);b.find("#show_per_page").val(e);e='<a class="previous_link" href="#"><i class="fa fa-angle-left"></i></a>';d=0;k=[];for(var l="",n="Page";a>d;)k[d]=d,10<a&&10<=d&&(l=" bsa_dn"),e+='<a class="page_link'+l+'" href="#" longdesc="'+d+'">'+(d+1)+"</a>",d++;1<a&&(n="Pages");e+='<a class="next_link" href="#"><i class="fa fa-angle-right"></i></a><br /><span class="total_pages">Total '+
a+" "+n+"</span>";b.find("#bsa_page_navigation").html("").html(e);0==h&&b.find("#bsa_page_navigation").remove();0==k.length?b.find("#bsa_page_navigation").css("display","none"):b.find("#bsa_page_navigation").css("display","block");b.find("#bsa_page_navigation .page_link:first").addClass("active_page");b.find(".next_link").on("click",function(){var a=parseInt(b.find("#current_page").val())+1,c=b.find(".active_page").next(".page_link");1==c.length&&(c.hasClass("bsa_dn")&&(c.removeClass("bsa_dn"),c=
parseInt(b.find("a.page_link:visible").length)-10,b.find("a.page_link:visible").slice(0,c).addClass("bsa_dn")),f.bsa_go_to_page(b,a));return!1});b.find(".previous_link").on("click",function(){var a=parseInt(b.find("#current_page").val())-1,c=b.find(".active_page").prev(".page_link"),e=b.find("div.bwl-faq-container").length,d=parseInt(b.find("a.page_link:visible:first").attr("longdesc"))-1,g=b.find("a.page_link:visible:last").attr("longdesc");if(1==c.length){if(-1<d&&g<e||0<=d)b.find("a.page_link").addClass("bsa_dn"),
b.find("a.page_link").slice(d,g).removeClass("bsa_dn");f.bsa_go_to_page(b,a)}return!1});b.find(".page_link").on("click",function(){var a=c(this).attr("longdesc");f.bsa_go_to_page(b,a);return!1})},bsa_go_to_page:function(b,c){var a=0;b.find("input[type=text]").length&&1<b.find("input[type=text]").val().length&&(a=1);var e=parseInt(b.find("#show_per_page").val()),f=c*e;e=f+e;1==a?b.find("section.filter").css("display","none").slice(f,e).css("display","block"):b.find("section").css("display","none").slice(f,
e).css("display","block");b.find(".page_link[longdesc="+c+"]").addClass("active_page").siblings(".active_page").removeClass("active_page");b.find("#current_page").val(c)},getThemeClasses:function(b){var c="",a="";""!=this.options.nav_icon&&(a=" nav_icon_"+this.options.nav_icon+"_active");1==this.options.rtl&&(c+=" rtl-title-active");return"theme-red"==b?{title_bar_class:"theme-red-title-bar",title_active_class:"theme-red-title-active"+a+c,nav_class:"red_theme_nav"}:"theme-green"==b?{title_bar_class:"theme-green-title-bar",
title_active_class:"theme-green-title-active"+a+c,nav_class:"green_theme_nav"}:"theme-blue"==b?{title_bar_class:"theme-blue-title-bar",title_active_class:"theme-blue-title-active"+a+c,nav_class:"blue_theme_nav"}:"theme-orange"==b?{title_bar_class:"theme-orange-title-bar",title_active_class:"theme-orange-title-active"+a+c,nav_class:"orange_theme_nav"}:"theme-yellow"==b?{title_bar_class:"theme-yellow-title-bar",title_active_class:"theme-yellow-title-active"+a+c,nav_class:"yellow_theme_nav"}:"custom"==
b?{title_bar_class:"theme-custom-title-bar",title_active_class:"theme-custom-title-active"+a+c,nav_class:"custom_theme_nav"}:{title_bar_class:"default-title-bar",title_active_class:"default-title-bar-active"+a+c,nav_class:"default_theme_nav"}},get_animation_class:function(){var b="animated ";b="flash"==this.options.animation?b+"flash":"shake"==this.options.animation?b+"shake":"tada"==this.options.animation?b+"tada":"swing"==this.options.animation?b+"swing":"wobble"==this.options.animation?b+"wobble":
"pulse"==this.options.animation?b+"pulse":"flipx"==this.options.animation?b+"flipInX":"faderight"==this.options.animation?b+"fadeInLeft":"fadeleft"==this.options.animation?b+"fadeInRight":"slide"==this.options.animation?b+"slideInRight":"slideup"==this.options.animation?b+"slideInDown":"bounce"==this.options.animation?b+"bounceIn":"lightspeed"==this.options.animation?b+"lightSpeedIn":"roll"==this.options.animation?b+"rollIn":"rotate"==this.options.animation?b+"rotateIn":"fade"==this.options.animation?
b+"fadeInDown":"none"==this.options.animation?"":b+"fadeIn";return[b]},toggleEvent:function(b,e,a,d){var f=this.options.toggle;b.hasClass(e.title_active_class)&&b.toggleClass(e.title_active_class).next().slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(a[0])});1==f&&(f=d.find(".acc_container"),d.find(".acc_title_bar").removeClass(e.title_active_class),f.slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(a[0])}));b.next().is(":hidden")&&(b.removeClass(e.title_active_class).next().slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(a[0])}),
b.toggleClass(e.title_active_class).next().slideDown(function(){c(this).find(".block").css({opacity:1}).addClass(a[0])}))},process_sbox_keys:function(){for(var b="",c=this.options.sbox_keywords.split(","),a=0;a<c.length;a++)b+='<a href="#">'+c[a]+"</a>, ";return b.substring(0,b.length-2)},searchEvent:function(b,e){var a=this,d,f,h,k=a.$elem.find(".search_result_container"),l=a.$elem.find(".accordion_search_input_box"),m=a.$elem;var q=1==a.options.rtl?m.find(".rtl_clear_btn"):m.find(".acc_clear_btn");
var r="",p="";1==a.options.rtl&&(r+=" search_icon_rtl",p+=" load_rtl");if(1==a.options.query_string)c(n).on("load",function(){var b=a.get_url_parameter("query");l.val(b).trigger("keyup")});if(1==a.options.suggestion_box){var t='<div class="suggestion_box"><span class="sbox_title">'+a.options.sbox_title+'</span> <span class="sbox_keywords">'+a.process_sbox_keys()+"</span></div>";a.$elem.find(".acc_clear_btn").after(t);a.$elem.find(".sbox_keywords").find("a").on("click",function(a){l.val(c(this).text()).trigger("keyup");
a.preventDefault()})}l.on("keyup",function(){h=c(this);h.addClass("load"+p);clearTimeout(f);clearTimeout(d);var g=c.trim(h.val());0==g.length&&q.removeAttr("style");2>g.length&&(h.removeClass("load"+p),a.$elem.find("section").removeAttr("class"),a.options.closeall?(a.$elem.find(".acc_title_bar").removeClass(b.title_active_class).slideDown(),a.$elem.find(".acc_container").slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(e[0])})):a.reset_acc_items(b,e),k.slideUp(),1==a.options.ctrl_btn&&
a.options.acc_ctrl_btn.slideDown(),a.options.pagination&&a.bsa_get_pagination_html(m,a.options.limit));f=2>g.length&&setTimeout(function(){a.removeHighlightEvent()},0);d=2<=g.length&&setTimeout(function(){var d=0;a.removeHighlightEvent();a.$elem.find(".acc_title_bar").each(function(){var f=c(this).find("a"),h=c(this).next(".acc_container").find("*");a.highlightEvent(f,g);if(!0===a.options.search_only_title)var k=c(this).text();else k=c(this).text()+c(this).next(".acc_container").text(),a.highlightEvent(h,
g);0>k.search(new RegExp(g,"gi"))?(c(this).removeClass(b.title_active_class).slideUp(),c(this).next().removeClass(b.title_active_class).slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(e[0])}),a.options.pagination&&c(this).next().parent("section").removeAttr("class")):(a.highlightEvent(f,g),!1===a.options.search_only_title&&a.highlightEvent(h,g),c(this).addClass(b.title_active_class).slideDown(),c(this).next().addClass(b.title_active_class).slideDown(function(){c(this).find(".block").css({opacity:1}).addClass(e[0])}),
a.options.pagination&&c(this).next().parent("section").addClass("filter"),d++)});if(0==d)q.css({display:"inline-block"}),k.html(a.options.msg_no_result).slideDown(function(){1==a.options.ctrl_btn&&a.options.acc_ctrl_btn.slideUp()}),a.options.pagination&&a.bsa_get_pagination_html(m,a.options.limit,d,1);else{q.css({display:"inline-block"});var f=a.$elem.find("i.highlight").length;k.html(f+a.options.msg_item_found).slideDown();a.options.pagination&&setTimeout(function(){m.find("section.filter").css({display:"block"});
a.bsa_get_pagination_html(m,a.options.limit,d,1)},200)}h.removeClass("load"+p);h.addClass("search_icon"+r)},200)})},resetAccordion:function(b,e,a){var d=this,f=b.find(".search_result_container");d.$elem.find("section").removeAttr("class");d.options.closeall?(d.$elem.find(".acc_title_bar").removeClass(e.title_active_class).slideDown(),d.$elem.find(".acc_container").slideUp(function(){c(this).find(".block").css({opacity:0}).removeClass(a[0])})):d.reset_acc_items(e,a);f.slideUp(function(){1==d.options.ctrl_btn&&
d.options.acc_ctrl_btn.slideDown()});d.options.pagination&&d.bsa_get_pagination_html(b,d.options.limit)},highlightEvent:function(b,c){b.highlightRegex(new RegExp(c,"gi"),{highlight_color:this.options.highlight_color,highlight_bg:this.options.highlight_bg})},removeHighlightEvent:function(){this.$elem.find("i.highlight").each(function(){c(this).replaceWith(c(this).text())})}};c.fn.bwlAccordion=function(b){return this.each(function(){Object.create(m).init(b,this)})};c.fn.bwlAccordion.config={search:!0,
placeholder:"Search .....",suggestion_box:!1,sbox_title:"Popular Searches:",sbox_keywords:"FAQ,Purchase",search_only_title:!1,theme:"default",title_bg:"#2c2c2c",title_text_color:"#FFFFFF",nav_box_bg:"#B8B831",title_active_bg:"#414141",title_active_text_color:"#F0F0F0",nav_active_box_bg:"#d0d051",animation:"fade",rtl:!1,msg_item_found:" Item(s) Found !",msg_no_result:"Nothing Found !",ctrl_btn:!1,toggle:!1,closeall:!0,item_opened:0,nav_box:"",nav_icon:"",highlight_bg:"#FFFF80",highlight_color:"#000000",
pagination:!1,limit:2,query_string:!1}})(jQuery,window,document);
(function(c){var n=function(h){if(h&&h.childNodes){var f=c.makeArray(h.childNodes),m=null;c.each(f,function(b,c){3===c.nodeType?""===c.nodeValue?h.removeChild(c):null!==m?(m.nodeValue+=c.nodeValue,h.removeChild(c)):m=c:(m=null,c.childNodes&&n(c))})}};c.fn.highlightRegex=function(h,f){"object"!==typeof h||"RegExp"==h.constructor.name||h instanceof RegExp||(f=h,h=void 0);"undefined"===typeof f&&(f={});f.className=f.className||"highlight";f.tagType=f.tagType||"i";f.highlight_color=f.highlight_color||
"";f.highlight_bg=f.highlight_bg||"";f.attrs=f.attrs||{};"undefined"===typeof h||""===h.source?c(this).find(f.tagType+"."+f.className).each(function(){c(this).replaceWith(c(this).text());n(c(this).parent().get(0))}):c(this).each(function(){var m=c(this).get(0);n(m);c.each(c.makeArray(m.childNodes),function(b,e){var a;n(e);if(3==e.nodeType){if(!c(e).parent(f.tagType+"."+f.className).length)for(;e.data&&0<=(a=e.data.search(h));){var d=e.data.slice(a).match(h)[0];if(0<d.length){var g=document.createElement(f.tagType);
g.className=f.className;g.style.backgroundColor=f.highlight_bg;g.style.color=f.highlight_color;c(g).attr(f.attrs);var m=e.parentNode;var k=e.splitText(a);e=k.splitText(d.length);d=k.cloneNode(!0);g.appendChild(d);m.replaceChild(g,k)}else break}}else c(e).highlightRegex(h,f)})});return c(this)}})(jQuery);